Something!

## Trajectory(-ies)

**trajectory**: A series of connected observations along a 1D curve in time and space. There can be multiple trajectories in the same file, each with a unique identifier. *Examples: aircraft data, drifting buoys*.

* [Only one trajectory in the file](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_single_trajectory)
* [All trajectories have the same number of points](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_multidimensional_array_representation_of_trajectories)
* Each trajectory has different number of points and we wanna keep file size as small as possible
    * [We have all the data already, and we wanna optimize reading all the data for one trajectory](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_contiguous_ragged_array_representation_of_trajectories)
    * [We wanna write the data as it arrives](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_indexed_ragged_array_representation_of_trajectories)

Example Datasets:
1. Only one trajectory in the file: [SWFSC Protected Resources Division CTD Data](https://coastwatch.pfeg.noaa.gov/erddap/tabledap/erdPrdCtd.html)
2. Multiple trajectories and each trajectory has different number of points: [SWFSC FED Mid Water Trawl Juvenile Rockfish Survey](https://coastwatch.pfeg.noaa.gov/erddap/tabledap/erdFedRockfishStation.html)

In [ ]:
import os
from glob import glob
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt

In [ ]:
os.chdir('/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data')
os.getcwd()

'/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data'

In [ ]:
file_trj = glob(os.path.join(os.getcwd(), "dsg_trajectory", "*.nc"))
file_trj

['/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_trajectory/rockfish_header_2015.nc',
 '/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_trajectory/rockfish_header_1987.nc',
 '/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_trajectory/PRD_ctd.nc']

In [ ]:
ds_trj1 = xr.open_dataset(file_trj[-1])
ds_trj1

<xarray.Dataset> Size: 101kB
Dimensions:             (row: 650)
Dimensions without coordinates: row
Data variables: (12/14)
    datetime            (row) |S19 12kB ...
    timestamp           (row) |S14 9kB ...
    lat                 (row) float32 3kB ...
    lon                 (row) float32 3kB ...
    prod                (row) float32 3kB ...
    chloro              (row) float32 3kB ...
    ...                  ...
    datetime_utc        (row) |S19 12kB ...
    datetime_utc_epoch  (row) float64 5kB ...
    geopoint            (row) |S50 32kB ...
    ship_station        (row) |S5 3kB ...
    lat1000             (row) float64 5kB ...
    lon1000             (row) float64 5kB ...
Attributes:
    id:                    PRD_ctd
    observationDimension:  row

In [ ]:
print(ds_trj1.datetime.data[0:3])
print(ds_trj1.timestamp.data[0:3])
print(ds_trj1.lat.data[0:3])
print(ds_trj1.lon.data[0:3])

print(ds_trj1.geopoint.data[0:3])
print(ds_trj1.ship_station.data[0:3])

[b'1998-09-01 10:39:00' b'1998-09-02 10:38:00' b'1998-09-03 10:46:00']
[b'19980901103900' b'19980902103800' b'19980903104600']
[12.56  11.447  9.688]
[-88.157 -86.663 -85.62 ]
[b'0101000020E6100000355EBA490C0A56C01F85EB51B81E2940'
 b'0101000020E6100000DF4F8D976EAA55C0BE9F1A2FDDE42640'
 b'0101000020E610000048E17A14AE6755C0C74B378941602340']
[b'1-044' b'1-046' b'1-048']


In [ ]:
ds_trj2 = xr.open_dataset(file_trj[0])
ds_trj2

<xarray.Dataset> Size: 44kB
Dimensions:             (row: 999)
Dimensions without coordinates: row
Data variables:
    cruise              (row) |S4 4kB ...
    ctd_index           (row) int16 2kB ...
    ctd_no              (row) int16 2kB ...
    station             (row) int16 2kB ...
    time                (row) datetime64[ns] 8kB ...
    latitude            (row) float32 4kB ...
    longitude           (row) float32 4kB ...
    bottom_depth        (row) int16 2kB ...
    bucket_temperature  (row) float32 4kB ...
    bucket_salinity     (row) float32 4kB ...
    ts_temperature      (row) float32 4kB ...
    ts_salinity         (row) float32 4kB ...
Attributes:
    id:       rockfish_header_2015

In [ ]:
ds_trj3 = xr.open_dataset(file_trj[1])
ds_trj3

<xarray.Dataset> Size: 15kB
Dimensions:             (row: 348)
Dimensions without coordinates: row
Data variables:
    cruise              (row) |S4 1kB ...
    ctd_index           (row) int16 696B ...
    ctd_no              (row) int16 696B ...
    station             (row) int16 696B ...
    time                (row) datetime64[ns] 3kB ...
    longitude           (row) float32 1kB ...
    latitude            (row) float32 1kB ...
    bottom_depth        (row) int16 696B ...
    bucket_temperature  (row) float32 1kB ...
    bucket_salinity     (row) float32 1kB ...
    ts_temperature      (row) float32 1kB ...
    ts_salinity         (row) float32 1kB ...
Attributes:
    id:       rockfish_header_1987

## Trajectory(-ies) of Profile(s)

**trajectory of profile(s)**: a collection of profile features which originate along a trajectory. So there are trajectories which have profile data (varying with z) at each (lat, lon) location. *Examples: ship soundings*.

* [Only one trajectory in the file](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_profiles_along_a_single_trajectory)
* [All trajectories have the same number of profiles, and the same number of vertical levels for each profile](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_multidimensional_array_representation_of_trajectory_profiles)
* [Each trajectory has different number of profiles AND/OR the vertical coordinate may vary](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_ragged_array_representation_of_trajectory_profiles)

Example Dataset: [GLOBEC NEP Rosette Bottle Data (2002)](https://coastwatch.pfeg.noaa.gov/erddap/tabledap/erdGlobecBottle.html)

In [ ]:
ds_trjPf = xr.open_dataset(os.path.join(os.getcwd(), "dsg_trjProfile", "Globec_bottle_data_2002.nc"))
ds_trjPf

<xarray.Dataset> Size: 534kB
Dimensions:         (row: 2205)
Dimensions without coordinates: row
Data variables: (12/37)
    date            (row) |S19 42kB ...
    yr              (row) float32 9kB ...
    ship            (row) |S11 24kB ...
    cruise_id       (row) |S6 13kB ...
    sta_std         (row) |S9 20kB ...
    cast_no         (row) float32 9kB ...
    ...              ...
    par             (row) float32 9kB ...
    datetime        (row) |S19 42kB ...
    datetime_epoch  (row) float64 18kB ...
    geopoint        (row) |S50 110kB ...
    lat100          (row) float32 9kB ...
    lon100          (row) float32 9kB ...
Attributes:
    id:                    Globec_bottle_data_2002
    observationDimension:  row

In [ ]:
print(ds_trjPf.date.data)
print(ds_trjPf.ship.data)
print(ds_trjPf.cruise_id.data)
print(ds_trjPf.lat.data)
print(ds_trjPf.lon.data)
print(ds_trjPf.datetime.data)
print(ds_trjPf.pressure.data)

[b'2002-05-29 00:00:00' b'2002-05-29 00:00:00' b'2002-05-29 00:00:00' ...
 b'2002-08-19 00:00:00' b'2002-08-19 00:00:00' b'2002-08-19 00:00:00']
[b'Wecoma' b'Wecoma' b'Wecoma' ... b'New_Horizon' b'New_Horizon'
 b'New_Horizon']
[b'w0205' b'w0205' b'w0205' ... b'nh0207' b'nh0207' b'nh0207']
[44.65 44.65 44.65 ... 44.65 44.65 44.65]
[-124.1 -124.1 -124.1 ... -124.1 -124.1 -124.1]
[b'2002-05-29 20:21:00' b'2002-05-29 20:21:00' b'2002-05-29 20:21:00' ...
 b'2002-08-19 13:18:00' b'2002-08-19 13:18:00' b'2002-08-19 13:18:00']
[22.606 15.754 10.235 ... 20.    10.     5.   ]
