# Discrete Sampling Geometries (DSG) netCDF in the CF Conventions

The examples in the previous chapters all concern netCDF files with grid data. In this chapter, we are going to learn about discrete sampling geometries (DSG) data and how they should look like in a netCDF file complied with the CF Conventions.

## DSG Types

DSG netCDF is the type of a netCDF file that stores a collection of **"features"** in a single file, where the "features" can be one of the following types:

* **Point(s)**: Data is located at different, unconnected locations, e.g. earthquake data, lightning data.

* **Time Series**: Data is located at named locations, called stations, each has a unique identifier. There can be multiple stations, and ususally for each station we have multiple data with different time coordinates. Examples are weather stations data, fixed buoys.

* **Profile(s)**: A series of connected observations along a vertical line. Each profile has only one lat, lon coordinate (possibly nominal), so that the points along the profile differ only in z coordinate and possibly time coodinate. There can be multiple profiles in the same file, and each profile has a unique identifier. If we have many profiles with the same lat, lon location, use the Time Series Profile type. *Examples: atomospheric profiles from satellites, moving profilers*.

* **Time Series of Profile(s)**: Time series of profiles at fixed locations. A file can contain many stations and many time series at each station. *Examples: profilers, balloon soundings*.

* **Trajectory**: A series of connected observations along a 1D curve in time and space. There can be multiple trajectories in the same file, each with a unique identifier. *Examples: aircraft data, drifting buoys*.

* **Trajectory of Profile(s)**: a collection of profile features which originate along a trajectory. So there are trajectories which have profile data (varying with z) at each (lat, lon) location. *Examples: ship soundings*.



In [9]:
import os
from glob import glob
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt

In [3]:
os.chdir('/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data')
os.getcwd()

'/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data'

## Point(s)

Example Dataset: [North Pacific High](https://coastwatch.pfeg.noaa.gov/erddap/tabledap/erdNph.html)

In [4]:
ds_nph = xr.open_dataset(os.path.join(os.getcwd(), "dsg_point", "NPH_IDS.nc"))
ds_nph.info()

xarray.Dataset {
dimensions:
	time = 565 ;

variables:
	datetime64[ns] time(time) ;
		time:long_name = Centered Time ;
	int16 year(time) ;
		year:long_name = Year ;
	int8 month(time) ;
		month:long_name = Month (1 - 12) ;
	float32 longitude(time) ;
		longitude:long_name = Longitude of the Center of the NPH ;
		longitude:units = degrees_east ;
	float32 latitude(time) ;
		latitude:long_name = Latitude of the Center of the NPH ;
		latitude:units = degrees_north ;
	float32 area(time) ;
		area:long_name = Areal Extent of the 1020 hPa Contour ;
		area:units = km2 ;
	float32 maxSLP(time) ;
		maxSLP:long_name = Maximum Sea Level Pressure ;
		maxSLP:units = hPa ;

// global attributes:
	:id = NPH_IDS ;
}

In [6]:
os.path.join(os.getcwd(), "dsg_point", "NPH_IDS.nc")

'/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_point/NPH_IDS.nc'

### point text --> netCDF

In [10]:
df_haulCatch = pd.read_csv(os.path.join(os.getcwd(), "dsg_point", "CPS_Trawl_LifeHistory_Haulcatch.csv"))
df_haulCatch

cruise ship  haul  collection  start_latitude  start_longitude  \
0      200307   FR     1        2003         42.9816        -124.8413   
1      200307   FR     1        2003         42.9816        -124.8413   
2      200307   FR     1        2003         42.9816        -124.8413   
3      200307   FR     1        2003         42.9816        -124.8413   
4      200307   FR     1        2003         42.9816        -124.8413   
...       ...  ...   ...         ...             ...              ...   
18081  202307   SH    81        4616         48.1445        -125.6153   
18082  202307   SH    81        4616         48.1445        -125.6153   
18083  202307   SH    81        4616         48.1445        -125.6153   
18084  202307   SH    81        4616         48.1445        -125.6153   
18085  202307   SH    81        4616         48.1445        -125.6153   

       stop_latitude  stop_longitude        equilibrium_time  \
0            43.0006       -124.8930  2003-07-08T21:03:00-07   
1            43.0006       -124.8930  2003-07-08T21:03:00-07   
2            43.0006       -124.8930  2003-07-08T21:03:00-07   
3            43.0006       -124.8930  2003-07-08T21:03:00-07   
4            43.0006       -124.8930  2003-07-08T21:03:00-07   
...              ...             ...                     ...   
18081        48.1073       -125.5773  2023-11-01T01:03:00-08   
18082        48.1073       -125.5773  2023-11-01T01:03:00-08   
18083        48.1073       -125.5773  2023-11-01T01:03:00-08   
18084        48.1073       -125.5773  2023-11-01T01:03:00-08   
18085        48.1073       -125.5773  2023-11-01T01:03:00-08   

                haulback_time  surface_temp surface_temp_method  \
0      2003-07-08T21:34:00-07          13.3              bucket   
1      2003-07-08T21:34:00-07          13.3              bucket   
2      2003-07-08T21:34:00-07          13.3              bucket   
3      2003-07-08T21:34:00-07          13.3              bucket   
4      2003-07-08T21:34:00-07          13.3              bucket   
...                       ...           ...                 ...   
18081  2023-11-01T01:48:00-08          13.6                 TSG   
18082  2023-11-01T01:48:00-08          13.6                 TSG   
18083  2023-11-01T01:48:00-08          13.6                 TSG   
18084  2023-11-01T01:48:00-08          13.6                 TSG   
18085  2023-11-01T01:48:00-08          13.6                 TSG   

       ship_spd_through_water  itis_tsn                  scientific_name  \
0                         3.5     82367                         Teuthida   
1                         3.5     82371  Doryteuthis (Loligo) opalescens   
2                         3.5    159643                          Salpida   
3                         3.5    161729                  Sardinops sagax   
4                         3.5    161828                 Engraulis mordax   
...                       ...       ...                              ...   
18081                     3.8    551209                  Clupea pallasii   
18082                     3.8     50623                         Aequorea   
18083                     3.8     51671                 Cyanea capillata   
18084                     3.8    161977             Oncorhynchus kisutch   
18085                     3.8    161729                  Sardinops sagax   

       subsample_count  subsample_weight  remaining_weight  
0                  1.0            0.0100               NaN  
1                  3.0            0.0300               NaN  
2                  NaN            0.1000               NaN  
3                  NaN            0.0100               NaN  
4                  NaN            0.0500               NaN  
...                ...               ...               ...  
18081              9.0            0.3180               0.0  
18082              2.0            0.1100               0.0  
18083              4.0            0.3500               0.0  
18084              3.0           

In [19]:
len(set(df_haulCatch['cruise']))

34

## Time Series

Example Dataset: [Kelp Forest Monitoring Sea Temperature](https://coastwatch.pfeg.noaa.gov/erddap/tabledap/erdCinpKfmT.html)

In [7]:
ts_files = glob(os.path.join(os.getcwd(), "dsg_timeSeries", "*.nc"))
ts_files

['/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_timeSeries/KFMTemperature_Anacapa_Cathedral_Cove.nc',
 '/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_timeSeries/KFMTemperature_Anacapa_Black_Sea_Bass_Reef.nc']

In [12]:
ds_ts1 = xr.open_dataset(ts_files[0])

print(ds_ts1["ID"].data)
ds_ts1

b'Anacapa (Cathedral Cove)'


<xarray.Dataset> Size: 1MB
Dimensions:      (LON: 1, LAT: 1, DEPTH: 1, TIME: 113457)
Coordinates:
  * LON          (LON) float32 4B -119.4
  * LAT          (LAT) float32 4B 34.0
  * DEPTH        (DEPTH) int32 4B 6
  * TIME         (TIME) datetime64[ns] 908kB 1993-10-01T19:48:00 ... 2007-07-...
Data variables:
    Temperature  (TIME, DEPTH, LAT, LON) float32 454kB ...
    ID           |S24 24B b'Anacapa (Cathedral Cove)'
Attributes: (12/38)
    acknowledgement:               NOAA NESDIS COASTWATCH, NOAA SWFSC ERD
    cdm_data_type:                 Station
    contributor_name:              Channel Islands National Park, National Pa...
    contributor_role:              Source of data.
    Conventions:                   COARDS, CF-1.0, Unidata Observation Datase...
    creator_email:                 Roy.Mendelssohn@noaa.gov
    ...                            ...
    standard_name_vocabulary:      CF-1.0
    summary:                       The subtidal temperature data taken at Cha...
    time_coverage_end:             2007-07-17T20:42:00Z
    time_coverage_start:           1993-10-01T19:48:00Z
    title:                         Sea Temperature (Kelp Forest Monitoring, C...
    Westernmost_Easting:           -119.36667

In [13]:
ds_ts2 = xr.open_dataset(ts_files[1])

print(ds_ts2['ID'].data)
ds_ts2

b'Anacapa (Black Sea Bass Reef)'


<xarray.Dataset> Size: 193kB
Dimensions:      (LON: 1, LAT: 1, DEPTH: 1, TIME: 16065)
Coordinates:
  * LON          (LON) float32 4B -119.4
  * LAT          (LAT) float32 4B 34.0
  * DEPTH        (DEPTH) int32 4B 17
  * TIME         (TIME) datetime64[ns] 129kB 2005-10-20T17:32:00 ... 2007-08-...
Data variables:
    Temperature  (TIME, DEPTH, LAT, LON) float32 64kB ...
    ID           |S29 29B b'Anacapa (Black Sea Bass Reef)'
Attributes: (12/38)
    acknowledgement:               NOAA NESDIS COASTWATCH, NOAA SWFSC ERD
    cdm_data_type:                 Station
    contributor_name:              Channel Islands National Park, National Pa...
    contributor_role:              Source of data.
    Conventions:                   COARDS, CF-1.0, Unidata Observation Datase...
    creator_email:                 Roy.Mendelssohn@noaa.gov
    ...                            ...
    standard_name_vocabulary:      CF-1.0
    summary:                       The subtidal temperature data taken at Cha...
    time_coverage_end:             2007-08-21T00:42:00Z
    time_coverage_start:           2005-10-20T17:32:00Z
    title:                         Sea Temperature (Kelp Forest Monitoring, C...
    Westernmost_Easting:           -119.38333

## Profile(s)

Example Dataset: [CTD profile ANTARES station (NetCDF files) (lat/long : 42.485/6.06)](https://erddap.osupytheas.fr/erddap/tabledap/CTD_Antares_NC_6fad_a064_dc26.html)

In [14]:
pf_files = glob(os.path.join(os.getcwd(), "dsg_profile", "*.nc"))
pf_files

['/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_profile/20180917_ctd0268_moose11.nc',
 '/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_profile/20170411_ctd0268_moose11.nc']

In [15]:
ds_pf1 = xr.open_dataset(pf_files[0])
ds_pf1

<xarray.Dataset> Size: 116kB
Dimensions:       (depth: 2409)
Coordinates:
    time          datetime64[ns] 8B ...
    latitude      float32 4B ...
    longitude     float32 4B ...
  * depth         (depth) float32 10kB -2.0 -3.0 -4.0 ... -2.376e+03 -2.377e+03
Data variables:
    stationname   |S7 7B ...
    pressure      (depth) float32 10kB ...
    temperature   (depth) float32 10kB ...
    conductivity  (depth) float32 10kB ...
    salinity      (depth) float32 10kB ...
    fluorescence  (depth) float32 10kB ...
    timeJ         (depth) float32 10kB ...
    irradiance    (depth) float32 10kB ...
    transmission  (depth) float32 10kB ...
    density       (depth) float32 10kB ...
    oxygenml      (depth) float32 10kB ...
    oxygenmol     (depth) float32 10kB ...
Attributes: (12/39)
    description:              CTD profile (NetCDF files) for station ANTARES
    title:                    CTD profile (NetCDF files) station ANTARES - Se...
    keywords:                 Seabird CTD temperature, conductivity, fluorime...
    history:                  Created 01/04/20
    production:               MIO UMR 7294 CNRS / OSU Pytheas UMS3470 CNRS
    contact:                  Christian Grenz (christian.grenz@mio.osupytheas...
    ...                       ...
    project:                  SOMLIT
    publisher_name:           MIO Marine Institute of Oceanography - OSU Pytheas
    publisher_email:          maurice.libes@osupytheas.fr
    publisher_url:            http://www.osupytheas.fr
    publisher_institution:    MIO UMR 7294 CNRS / OSU Pytheas UMS 3470 CNRS
    program:                  SOMLIT Service d’Observation en Milieu Littoral

In [16]:
ds_pf2 = xr.open_dataset(pf_files[1])
ds_pf2

<xarray.Dataset> Size: 120kB
Dimensions:       (depth: 2502)
Coordinates:
    time          datetime64[ns] 8B ...
    latitude      float32 4B ...
    longitude     float32 4B ...
  * depth         (depth) float32 10kB -2.0 -3.0 -4.0 ... -2.468e+03 -2.468e+03
Data variables:
    stationname   |S7 7B ...
    pressure      (depth) float32 10kB ...
    temperature   (depth) float32 10kB ...
    conductivity  (depth) float32 10kB ...
    salinity      (depth) float32 10kB ...
    fluorescence  (depth) float32 10kB ...
    timeJ         (depth) float32 10kB ...
    irradiance    (depth) float32 10kB ...
    transmission  (depth) float32 10kB ...
    density       (depth) float32 10kB ...
    oxygenml      (depth) float32 10kB ...
    oxygenmol     (depth) float32 10kB ...
Attributes: (12/39)
    description:              CTD profile (NetCDF files) for station ANTARES
    title:                    CTD profile (NetCDF files) station ANTARES - Se...
    keywords:                 Seabird CTD temperature, conductivity, fluorime...
    history:                  Created 01/04/20
    production:               MIO UMR 7294 CNRS / OSU Pytheas UMS3470 CNRS
    contact:                  Christian Grenz (christian.grenz@mio.osupytheas...
    ...                       ...
    project:                  SOMLIT
    publisher_name:           MIO Marine Institute of Oceanography - OSU Pytheas
    publisher_email:          maurice.libes@osupytheas.fr
    publisher_url:            http://www.osupytheas.fr
    publisher_institution:    MIO UMR 7294 CNRS / OSU Pytheas UMS 3470 CNRS
    program:                  SOMLIT Service d’Observation en Milieu Littoral

In [19]:
print(ds_pf1.time.data)
print(ds_pf1.latitude.data)
print(ds_pf1.longitude.data)
print(ds_pf1.stationname.data)

print(ds_pf2.time.data)
print(ds_pf2.latitude.data)
print(ds_pf2.longitude.data)
print(ds_pf2.stationname.data)

2018-09-17T08:34:00.000000000
42.81
6.11
b'ANTARES'
2017-04-11T08:42:00.000000000
42.8
6.14
b'ANTARES'


## Time Series of Profile(s)

Example Dataset: [Newport Lab CTD Casts, 1997-2008](https://coastwatch.pfeg.noaa.gov/erddap/tabledap/erdNewportCtd.html)

In [20]:
file_tsProfile = glob(os.path.join(os.getcwd(), "dsg_tsProfile", "*.nc"))
file_tsProfile

['/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_tsProfile/061207NH01.nc',
 '/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_tsProfile/061207NH03.nc',
 '/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_tsProfile/061298NH01.nc']

In [23]:
ds_ctd1 = xr.open_dataset(file_tsProfile[2])
ds_ctd1

<xarray.Dataset> Size: 28kB
Dimensions:            (row: 266)
Dimensions without coordinates: row
Data variables: (12/14)
    line               (row) |S2 532B ...
    longitude          (row) float64 2kB ...
    latitude           (row) float64 2kB ...
    station_code       (row) |S10 3kB ...
    time               (row) datetime64[ns] 2kB ...
    station            (row) |S4 1kB ...
    ...                 ...
    temperature        (row) float64 2kB ...
    salinity           (row) float64 2kB ...
    density            (row) float64 2kB ...
    fluorescence       (row) float64 2kB ...
    project            (row) |S2 532B ...
    transect           (row) |S20 5kB ...
Attributes:
    id:                    061298NH01
    observationDimension:  row

In [24]:
ds_ctd2 = xr.open_dataset(file_tsProfile[0])
ds_ctd2

<xarray.Dataset> Size: 57kB
Dimensions:            (row: 519)
Dimensions without coordinates: row
Data variables: (12/14)
    line               (row) |S2 1kB ...
    longitude          (row) float64 4kB ...
    latitude           (row) float64 4kB ...
    station_code       (row) |S10 5kB ...
    time               (row) datetime64[ns] 4kB ...
    station            (row) |S4 2kB ...
    ...                 ...
    temperature        (row) float64 4kB ...
    salinity           (row) float64 4kB ...
    density            (row) float64 4kB ...
    fluorescence       (row) float64 4kB ...
    project            (row) |S6 3kB ...
    transect           (row) |S20 10kB ...
Attributes:
    id:                    061207NH01
    observationDimension:  row

In [25]:
ds_ctd3 = xr.open_dataset(file_tsProfile[1])
ds_ctd3

<xarray.Dataset> Size: 2kB
Dimensions:            (row: 19)
Dimensions without coordinates: row
Data variables: (12/14)
    line               (row) |S2 38B ...
    longitude          (row) float64 152B ...
    latitude           (row) float64 152B ...
    station_code       (row) |S10 190B ...
    time               (row) datetime64[ns] 152B ...
    station            (row) |S4 76B ...
    ...                 ...
    temperature        (row) float64 152B ...
    salinity           (row) float64 152B ...
    density            (row) float64 152B ...
    fluorescence       (row) float64 152B ...
    project            (row) |S2 38B ...
    transect           (row) |S20 380B ...
Attributes:
    id:                    061207NH03
    observationDimension:  row

In [31]:
print(ds_ctd1.id, ds_ctd1.time.data[0], ds_ctd1.station.data[0], ds_ctd1.latitude.data[0], ds_ctd1.longitude.data[0])
print(ds_ctd2.id, ds_ctd2.time.data[0], ds_ctd2.station.data[0], ds_ctd2.latitude.data[0], ds_ctd2.longitude.data[0])
print(ds_ctd3.id, ds_ctd3.time.data[0], ds_ctd3.station.data[0], ds_ctd3.latitude.data[0], ds_ctd3.longitude.data[0])

061298NH01 2007-06-13T04:32:00.000000000 b'NH25' 44.65169887200318 -124.64999685107614
061207NH01 2000-06-12T18:17:00.000000000 b'NH45' 44.65169887200318 -125.1166968392863
061207NH03 2007-06-13T00:26:00.000000000 b'NH01' 44.65169887200318 -124.09999686497031


In [41]:
# Each station has a different number of profiles AND the level coordinates for each station vary
print(ds_ctd1.depth_or_pressure.data[-5:-1])
print(ds_ctd2.depth_or_pressure.data[-5:-1])
print(ds_ctd3.depth_or_pressure.data[-5:-1])

[261.99999338 262.99999336 263.99999333 264.99999331]
[513.99998702 514.99998699 515.99998696 516.99998694]
[14.99999962 15.9999996  16.99999957 17.99999955]


## Trajectory(-ies)

Example Datasets:
1. Only one trajectory in the file: [SWFSC Protected Resources Division CTD Data](https://coastwatch.pfeg.noaa.gov/erddap/tabledap/erdPrdCtd.html)
2. Multiple trajectories and each trajectory has different number of points: [SWFSC FED Mid Water Trawl Juvenile Rockfish Survey](https://coastwatch.pfeg.noaa.gov/erddap/tabledap/erdFedRockfishStation.html)

In [54]:
file_trj = glob(os.path.join(os.getcwd(), "dsg_trajectory", "*.nc"))
file_trj

['/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_trajectory/rockfish_header_2015.nc',
 '/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_trajectory/rockfish_header_1987.nc',
 '/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_trajectory/PRD_ctd.nc']

In [55]:
ds_trj1 = xr.open_dataset(file_trj[-1])
ds_trj1

<xarray.Dataset> Size: 101kB
Dimensions:             (row: 650)
Dimensions without coordinates: row
Data variables: (12/14)
    datetime            (row) |S19 12kB ...
    timestamp           (row) |S14 9kB ...
    lat                 (row) float32 3kB ...
    lon                 (row) float32 3kB ...
    prod                (row) float32 3kB ...
    chloro              (row) float32 3kB ...
    ...                  ...
    datetime_utc        (row) |S19 12kB ...
    datetime_utc_epoch  (row) float64 5kB ...
    geopoint            (row) |S50 32kB ...
    ship_station        (row) |S5 3kB ...
    lat1000             (row) float64 5kB ...
    lon1000             (row) float64 5kB ...
Attributes:
    id:                    PRD_ctd
    observationDimension:  row

In [56]:
print(ds_trj1.datetime.data[0:3])
print(ds_trj1.timestamp.data[0:3])
print(ds_trj1.lat.data[0:3])
print(ds_trj1.lon.data[0:3])

print(ds_trj1.geopoint.data[0:3])
print(ds_trj1.ship_station.data[0:3])

[b'1998-09-01 10:39:00' b'1998-09-02 10:38:00' b'1998-09-03 10:46:00']
[b'19980901103900' b'19980902103800' b'19980903104600']
[12.56  11.447  9.688]
[-88.157 -86.663 -85.62 ]
[b'0101000020E6100000355EBA490C0A56C01F85EB51B81E2940'
 b'0101000020E6100000DF4F8D976EAA55C0BE9F1A2FDDE42640'
 b'0101000020E610000048E17A14AE6755C0C74B378941602340']
[b'1-044' b'1-046' b'1-048']


In [57]:
ds_trj2 = xr.open_dataset(file_trj[0])
ds_trj2

<xarray.Dataset> Size: 44kB
Dimensions:             (row: 999)
Dimensions without coordinates: row
Data variables:
    cruise              (row) |S4 4kB ...
    ctd_index           (row) int16 2kB ...
    ctd_no              (row) int16 2kB ...
    station             (row) int16 2kB ...
    time                (row) datetime64[ns] 8kB ...
    latitude            (row) float32 4kB ...
    longitude           (row) float32 4kB ...
    bottom_depth        (row) int16 2kB ...
    bucket_temperature  (row) float32 4kB ...
    bucket_salinity     (row) float32 4kB ...
    ts_temperature      (row) float32 4kB ...
    ts_salinity         (row) float32 4kB ...
Attributes:
    id:       rockfish_header_2015

In [58]:
ds_trj3 = xr.open_dataset(file_trj[1])
ds_trj3

<xarray.Dataset> Size: 15kB
Dimensions:             (row: 348)
Dimensions without coordinates: row
Data variables:
    cruise              (row) |S4 1kB ...
    ctd_index           (row) int16 696B ...
    ctd_no              (row) int16 696B ...
    station             (row) int16 696B ...
    time                (row) datetime64[ns] 3kB ...
    longitude           (row) float32 1kB ...
    latitude            (row) float32 1kB ...
    bottom_depth        (row) int16 696B ...
    bucket_temperature  (row) float32 1kB ...
    bucket_salinity     (row) float32 1kB ...
    ts_temperature      (row) float32 1kB ...
    ts_salinity         (row) float32 1kB ...
Attributes:
    id:       rockfish_header_1987

## Trajectory(-ies) of Profile(s)

Example Dataset: [GLOBEC NEP Rosette Bottle Data (2002)](https://coastwatch.pfeg.noaa.gov/erddap/tabledap/erdGlobecBottle.html)

In [59]:
ds_trjPf = xr.open_dataset(os.path.join(os.getcwd(), "dsg_trjProfile", "Globec_bottle_data_2002.nc"))
ds_trjPf

<xarray.Dataset> Size: 534kB
Dimensions:         (row: 2205)
Dimensions without coordinates: row
Data variables: (12/37)
    date            (row) |S19 42kB ...
    yr              (row) float32 9kB ...
    ship            (row) |S11 24kB ...
    cruise_id       (row) |S6 13kB ...
    sta_std         (row) |S9 20kB ...
    cast_no         (row) float32 9kB ...
    ...              ...
    par             (row) float32 9kB ...
    datetime        (row) |S19 42kB ...
    datetime_epoch  (row) float64 18kB ...
    geopoint        (row) |S50 110kB ...
    lat100          (row) float32 9kB ...
    lon100          (row) float32 9kB ...
Attributes:
    id:                    Globec_bottle_data_2002
    observationDimension:  row

In [74]:
print(ds_trjPf.date.data)
print(ds_trjPf.ship.data)
print(ds_trjPf.cruise_id.data)
print(ds_trjPf.lat.data)
print(ds_trjPf.lon.data)
print(ds_trjPf.datetime.data)
print(ds_trjPf.pressure.data)

[b'2002-05-29 00:00:00' b'2002-05-29 00:00:00' b'2002-05-29 00:00:00' ...
 b'2002-08-19 00:00:00' b'2002-08-19 00:00:00' b'2002-08-19 00:00:00']
[b'Wecoma' b'Wecoma' b'Wecoma' ... b'New_Horizon' b'New_Horizon'
 b'New_Horizon']
[b'w0205' b'w0205' b'w0205' ... b'nh0207' b'nh0207' b'nh0207']
[44.65 44.65 44.65 ... 44.65 44.65 44.65]
[-124.1 -124.1 -124.1 ... -124.1 -124.1 -124.1]
[b'2002-05-29 20:21:00' b'2002-05-29 20:21:00' b'2002-05-29 20:21:00' ...
 b'2002-08-19 13:18:00' b'2002-08-19 13:18:00' b'2002-08-19 13:18:00']
[22.606 15.754 10.235 ... 20.    10.     5.   ]
