## Profile(s)

**profile**: A series of connected observations along a vertical line. Each profile has only one lat, lon coordinate (possibly nominal), so that the points along the profile differ only in z coordinate and possibly time coodinate. There can be multiple profiles in the same file, and each profile has a unique identifier. If we have many profiles with the same lat, lon location, use the Time Series Profile type. *Examples: atomospheric profiles from satellites, moving profilers*.

* [Only one profile in the file](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_single_profile)
* [All profiles have the same vertical coordinates](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_orthogonal_multidimensional_array_representation_of_profiles)
* [Each profile has the same number of vertical coordinates but the coordinate values may be different](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_incomplete_multidimensional_array_representation_of_profiles)
* Each profile has a different number of vertical coordinates and we wanna keep file size as small as possible:
    * [we have all the data already, and we wanna optimize reading all the data for one profile](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_contiguous_ragged_array_representation_of_profiles)
    * [we wanna write the data as it arrives, in any order](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_indexed_ragged_array_representation_of_profiles)
        * *double time(profile) is possible*; *double time(obs)* is also possible, when the observation varies by time. 


Example Dataset: [CTD profile ANTARES station (NetCDF files) (lat/long : 42.485/6.06)](https://erddap.osupytheas.fr/erddap/tabledap/CTD_Antares_NC_6fad_a064_dc26.html)

In [ ]:
import os
from glob import glob
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt

In [ ]:
os.chdir('/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data')
os.getcwd()

'/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data'

In [ ]:
pf_files = glob(os.path.join(os.getcwd(), "dsg_profile", "*.nc"))
pf_files

['/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_profile/20180917_ctd0268_moose11.nc',
 '/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_profile/20170411_ctd0268_moose11.nc']

In [ ]:
ds_pf1 = xr.open_dataset(pf_files[0])
ds_pf1

<xarray.Dataset> Size: 116kB
Dimensions:       (depth: 2409)
Coordinates:
    time          datetime64[ns] 8B ...
    latitude      float32 4B ...
    longitude     float32 4B ...
  * depth         (depth) float32 10kB -2.0 -3.0 -4.0 ... -2.376e+03 -2.377e+03
Data variables:
    stationname   |S7 7B ...
    pressure      (depth) float32 10kB ...
    temperature   (depth) float32 10kB ...
    conductivity  (depth) float32 10kB ...
    salinity      (depth) float32 10kB ...
    fluorescence  (depth) float32 10kB ...
    timeJ         (depth) float32 10kB ...
    irradiance    (depth) float32 10kB ...
    transmission  (depth) float32 10kB ...
    density       (depth) float32 10kB ...
    oxygenml      (depth) float32 10kB ...
    oxygenmol     (depth) float32 10kB ...
Attributes: (12/39)
    description:              CTD profile (NetCDF files) for station ANTARES
    title:                    CTD profile (NetCDF files) station ANTARES - Se...
    keywords:                 Seabird CTD temperature, conductivity, fluorime...
    history:                  Created 01/04/20
    production:               MIO UMR 7294 CNRS / OSU Pytheas UMS3470 CNRS
    contact:                  Christian Grenz (christian.grenz@mio.osupytheas...
    ...                       ...
    project:                  SOMLIT
    publisher_name:           MIO Marine Institute of Oceanography - OSU Pytheas
    publisher_email:          maurice.libes@osupytheas.fr
    publisher_url:            http://www.osupytheas.fr
    publisher_institution:    MIO UMR 7294 CNRS / OSU Pytheas UMS 3470 CNRS
    program:                  SOMLIT Service d’Observation en Milieu Littoral

In [ ]:
ds_pf2 = xr.open_dataset(pf_files[1])
ds_pf2

<xarray.Dataset> Size: 120kB
Dimensions:       (depth: 2502)
Coordinates:
    time          datetime64[ns] 8B ...
    latitude      float32 4B ...
    longitude     float32 4B ...
  * depth         (depth) float32 10kB -2.0 -3.0 -4.0 ... -2.468e+03 -2.468e+03
Data variables:
    stationname   |S7 7B ...
    pressure      (depth) float32 10kB ...
    temperature   (depth) float32 10kB ...
    conductivity  (depth) float32 10kB ...
    salinity      (depth) float32 10kB ...
    fluorescence  (depth) float32 10kB ...
    timeJ         (depth) float32 10kB ...
    irradiance    (depth) float32 10kB ...
    transmission  (depth) float32 10kB ...
    density       (depth) float32 10kB ...
    oxygenml      (depth) float32 10kB ...
    oxygenmol     (depth) float32 10kB ...
Attributes: (12/39)
    description:              CTD profile (NetCDF files) for station ANTARES
    title:                    CTD profile (NetCDF files) station ANTARES - Se...
    keywords:                 Seabird CTD temperature, conductivity, fluorime...
    history:                  Created 01/04/20
    production:               MIO UMR 7294 CNRS / OSU Pytheas UMS3470 CNRS
    contact:                  Christian Grenz (christian.grenz@mio.osupytheas...
    ...                       ...
    project:                  SOMLIT
    publisher_name:           MIO Marine Institute of Oceanography - OSU Pytheas
    publisher_email:          maurice.libes@osupytheas.fr
    publisher_url:            http://www.osupytheas.fr
    publisher_institution:    MIO UMR 7294 CNRS / OSU Pytheas UMS 3470 CNRS
    program:                  SOMLIT Service d’Observation en Milieu Littoral

In [ ]:
print(ds_pf1.time.data)
print(ds_pf1.latitude.data)
print(ds_pf1.longitude.data)
print(ds_pf1.stationname.data)

print(ds_pf2.time.data)
print(ds_pf2.latitude.data)
print(ds_pf2.longitude.data)
print(ds_pf2.stationname.data)

2018-09-17T08:34:00.000000000
42.81
6.11
b'ANTARES'
2017-04-11T08:42:00.000000000
42.8
6.14
b'ANTARES'


## Time Series of Profile(s)

**time series (station) of profile(s)**: Time series of profiles at fixed locations. A file can contain many stations and many time series at each station. *Examples: profilers, balloon soundings*.
    
* [Only one station in the file](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_time_series_of_profiles_at_a_single_station)
* [Each station has the same number of profiles, and the same number of vertical levels for each profile](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_multidimensional_array_representations_of_time_series_profiles)
* [Each station has a different number of profiles AND/OR the level coordinates for each station may vary](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_ragged_array_representation_of_time_series_profiles)


Example Dataset: [Newport Lab CTD Casts, 1997-2008](https://coastwatch.pfeg.noaa.gov/erddap/tabledap/erdNewportCtd.html)

In [ ]:
file_tsProfile = glob(os.path.join(os.getcwd(), "dsg_tsProfile", "*.nc"))
file_tsProfile

['/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_tsProfile/061207NH01.nc',
 '/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_tsProfile/061207NH03.nc',
 '/Users/icdc/Documents/NFDI/Kemeng/cfbook/src/data/dsg_tsProfile/061298NH01.nc']

In [ ]:
ds_ctd1 = xr.open_dataset(file_tsProfile[2])
ds_ctd1

<xarray.Dataset> Size: 28kB
Dimensions:            (row: 266)
Dimensions without coordinates: row
Data variables: (12/14)
    line               (row) |S2 532B ...
    longitude          (row) float64 2kB ...
    latitude           (row) float64 2kB ...
    station_code       (row) |S10 3kB ...
    time               (row) datetime64[ns] 2kB ...
    station            (row) |S4 1kB ...
    ...                 ...
    temperature        (row) float64 2kB ...
    salinity           (row) float64 2kB ...
    density            (row) float64 2kB ...
    fluorescence       (row) float64 2kB ...
    project            (row) |S2 532B ...
    transect           (row) |S20 5kB ...
Attributes:
    id:                    061298NH01
    observationDimension:  row

In [ ]:
ds_ctd2 = xr.open_dataset(file_tsProfile[0])
ds_ctd2

<xarray.Dataset> Size: 57kB
Dimensions:            (row: 519)
Dimensions without coordinates: row
Data variables: (12/14)
    line               (row) |S2 1kB ...
    longitude          (row) float64 4kB ...
    latitude           (row) float64 4kB ...
    station_code       (row) |S10 5kB ...
    time               (row) datetime64[ns] 4kB ...
    station            (row) |S4 2kB ...
    ...                 ...
    temperature        (row) float64 4kB ...
    salinity           (row) float64 4kB ...
    density            (row) float64 4kB ...
    fluorescence       (row) float64 4kB ...
    project            (row) |S6 3kB ...
    transect           (row) |S20 10kB ...
Attributes:
    id:                    061207NH01
    observationDimension:  row

In [ ]:
ds_ctd3 = xr.open_dataset(file_tsProfile[1])
ds_ctd3

<xarray.Dataset> Size: 2kB
Dimensions:            (row: 19)
Dimensions without coordinates: row
Data variables: (12/14)
    line               (row) |S2 38B ...
    longitude          (row) float64 152B ...
    latitude           (row) float64 152B ...
    station_code       (row) |S10 190B ...
    time               (row) datetime64[ns] 152B ...
    station            (row) |S4 76B ...
    ...                 ...
    temperature        (row) float64 152B ...
    salinity           (row) float64 152B ...
    density            (row) float64 152B ...
    fluorescence       (row) float64 152B ...
    project            (row) |S2 38B ...
    transect           (row) |S20 380B ...
Attributes:
    id:                    061207NH03
    observationDimension:  row

In [ ]:
print(ds_ctd1.id, ds_ctd1.time.data[0], ds_ctd1.station.data[0], ds_ctd1.latitude.data[0], ds_ctd1.longitude.data[0])
print(ds_ctd2.id, ds_ctd2.time.data[0], ds_ctd2.station.data[0], ds_ctd2.latitude.data[0], ds_ctd2.longitude.data[0])
print(ds_ctd3.id, ds_ctd3.time.data[0], ds_ctd3.station.data[0], ds_ctd3.latitude.data[0], ds_ctd3.longitude.data[0])

061298NH01 2007-06-13T04:32:00.000000000 b'NH25' 44.65169887200318 -124.64999685107614
061207NH01 2000-06-12T18:17:00.000000000 b'NH45' 44.65169887200318 -125.1166968392863
061207NH03 2007-06-13T00:26:00.000000000 b'NH01' 44.65169887200318 -124.09999686497031


In [ ]:
# Each station has a different number of profiles AND the level coordinates for each station vary
print(ds_ctd1.depth_or_pressure.data[-5:-1])
print(ds_ctd2.depth_or_pressure.data[-5:-1])
print(ds_ctd3.depth_or_pressure.data[-5:-1])

[261.99999338 262.99999336 263.99999333 264.99999331]
[513.99998702 514.99998699 515.99998696 516.99998694]
[14.99999962 15.9999996  16.99999957 17.99999955]
